version: 2.1
jobs:
  start:
    docker:
      - image: circleci/node:10-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn
            yarn test:ci
workflows:
  version: 2
  Example_Workflow:
    jobs:
     - start

