version: 2.1
jobs:
  app:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Segunda Etapa
          command: |
            yarn start:dev
workflows:
  version: 2
  Example_Workflow:
    jobs:
      - app

